### ISSUE TITLE
Time out bug

### ISSUE THREAD

**Issue by smchamplin16** [BlakeCS-Spring2015/Bakken-Prototype#13]
After leaving the app idle for 2 minutes, the app times out and returns to the Touch to Begin screen. Touching the screen again after this brings the user to a blank screen (no nav bar, no images, nothing).

**Comment by weinshel** [comment]
Fixed in 1df27a9 thanks to help from Jonathan Solomon. The new code
is actually a lot simpler and just backs out to the root screen when
the time runs out
