### ISSUE TITLE
App crashes after tapping on image

### ISSUE THREAD

**Issue by smchamplin16** [BlakeCS-Spring2015/Bakken-Prototype#14]
Select an object from the object select view, then tap on the image to zoom in. The app crashes immediately and there is a SIGABRT in the main.m file after autoreleasepool. The last line in the console reads "libc++abi.dylib: terminating with uncaught exception of type NSException (lldb)"

**Comment by weinshel** [comment]
Fixed in 6f6fc9d8e40dd9169a27da1be46e0f57a6e3ff2f

We had a file again that wasn’t added to the build phase in the project
settings. This probably is related to poor execution of the merging of
the `project.pbxproj` file
