### ISSUE TITLE
Navigation Controller not showing on first start up

### ISSUE THREAD

**Issue by QuinnE** [BlakeCS-Spring2015/Bakken-Prototype#16]
The navigation controller bar with the color we set from the Bakken is not showing up the first time on the grid view. When you click on an exhibit item the bar shows up in the details viewcontroller and then is present in the grid view when you return to it from the detail viewcontroller, but doesn't show the first time.

**Comment by weinshel** [comment]
Fixed in ae210b5da54a0b03629accd14610167e145909b2 (sorry if I stole your issue)
