### ISSUE TITLE
Detail screen haphazardly laid out

### ISSUE THREAD

**Issue by weinshel** [BlakeCS-Spring2015/Bakken-Prototype#22]
Open the app, touch to begin, then select an object. The screen with the image and object details is really haphazardly laid out (some issues below)

- the image on the left isn't vertically centered
- the text on the right should be horizontally centered in the whitespace not taken up by the picture
- the order the labels are in is completely nonsensical
- some of the text is truncated like thi…

**Comment by QuinnE** [comment]
Fixed in #982d680
